### ISSUE TITLE
When running the code I am getting a lot of errors?

### ISSUE THREAD

**Issue by krish-shahh** [adrianhajdin/project_medical_pager_chat#26]
rror: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/krish/project_medical_pager_chat/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/krish/project_medical_pager_chat/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/krish/project_medical_pager_chat/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/krish/project_medical_pager_chat/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/krish/project_medical_pager_chat/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/krish/project_medical_pager_chat/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/krish/project_medical_pager_chat/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/krish/project_medical_pager_chat/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/krish/project_medical_pager_chat/client/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/krish/project_medical_pager_chat/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/krish/project_medical_pager_chat/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/krish/project_medical_pager_chat/client/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/krish/project_medical_pager_chat/client/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/krish/project_medical_pager_chat/client/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/krish/project_medical_pager_chat/client/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/krish/project_medical_pager_chat/client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/krish/project_medical_pager_chat/client/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by chillyen** [comment]
You have to update your node version to 16.14.0.
You can install nvm to get lower version.
