### ISSUE TITLE
Getting Two errors 

### ISSUE THREAD

**Issue by yashdalal07** [adrianhajdin/project_medical_pager_chat#29]
POST https://localhost:8000/auth/signup net::ERR_SSL_PROTOCOL_ERROR                                                       xhr.js:247          
Auth.jsx:50 Uncaught (in promise) AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
![Screenshot 2023-03-31 175032](https://user-images.githubusercontent.com/129296669/229118240-92cca624-78cf-4928-9d3f-6162491ca247.jpg)

**Comment by RahulAgnihotri2001** [comment]
Yash were you able to solve the error ?

**Comment by yashdalal07** [comment]
Yes

**Comment by PrtHub** [comment]
How did you solve this ?

**Comment by PrtHub** [comment]
> Yash were you able to solve the error ?

Did you solve this? if you do let me know, I faced the same error

**Comment by bernardyamoah** [comment]
I am also facing the same problem

**Comment by bernardyamoah** [comment]
> I am also facing the same problem

Could you please help us out

**Comment by yashdalal07** [comment]
Yeah I can help let me know when can we connect

**Comment by ayushman-03** [comment]
> POST https://localhost:8000/auth/signup net::ERR_SSL_PROTOCOL_ERROR xhr.js:247 Auth.jsx:50 Uncaught (in promise) AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …} ![Screenshot 2023-03-31 175032](https://user-images.githubusercontent.com/129296669/229118240-92cca624-78cf-4928-9d3f-6162491ca247.jpg)

Yash can u help me out with this same error

**Comment by winaung1** [comment]
(https://localhost:8000/auth/signup) delet the s from https instead use http://localhost:8000/auth/signup

**Comment by jahanvi1903** [comment]
> (https://localhost:8000/auth/signup) delet the s from https instead use http://localhost:8000/auth/signup

I got another error after changing can you please help


ERROR
Request failed with status code 500
    at createError (http://localhost:3000/static/js/bundle.js:8597:15)
    at settle (http://localhost:3000/static/js/bundle.js:8851:12)
    at XMLHttpRequest.onloadend (http://localhost:3000/static/js/bundle.js:7983:7)

**Comment by yashdalal07** [comment]
Sure

**Comment by winaung1** [comment]
Hey go to my repo and take a look at what I did.
https://winrealtor.netlify.app. Here is the live site, I made some changes to the original one.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mayankmishra786** [comment]
Even after changing URL by removing s, it's giving me an error with status code 404. Did anyone resolve this issue?
